### ISSUE TITLE
My experiences with vAmiga-core 2.6beta.. a lot has improved yet there are some issues..

### ISSUE THREAD

**Issue by PTz0uAH** [vAmigaWeb/uat#3]
Hoi @mithrendal..

Here some remarks about 2.6beta.. running also at https://amigoxpe.net/uat/AmiGoDOS.php test domain..

3 HDFs and 1 ADF were created to demonstrate the productivity mode I want to work with from poweruser/dev perspective:

Once I cloned the 90s WB HDDs from my real A1230, A3060PPC (before I sold the whole collection in the first decade after the millenium-change..) and used the HDFs over and over..  trying to recreate that mystifying experience from back in the day..

Here I use the "souped up" A1200 disk as vAmigaWeb-boot-disk (DH0:) and disabled the Phase5 Blizzard 1230 IV stuff in the Startup-Sequence (works in Fs-uae/WinUAE)..

- DH0: 128MB for Workbench 3.1 + Scala MM-400 + SC 6.58 + Blitz2 + VBCC  & more..
- DH10: 50MB reserved for a special "vAmigaWeb" WIP build of a pre-configured Dopus5.92 (hi-res 16 col gfx) running as WB replacement.. and surrogate IDE for AmiBlitz :-)
- DH20: 50MB dedicated to test the latest vanilla AmiBlitz3.9.10..
- DF0: Projects Floppy with Blitz projects

Configured vAmigaWeb maxed-out.. which means 68020E CPU 14/28Mhz for best performance..

This is what I experienced (ootb).. using primarely my "TheLegacyBrowser" (Chromium 122).. and FireFox for comparence..

Positive Aspects:
1. "coldboot" faster than with 2.4 to the Dopus5 desktop..
2. accepts more than 2 HDFs..
3. ScalaMM runs at full speed.. all demo scripts work.. so we can control it with Arexx via AUX: to the AmiGoDOS(web) shell and even to the native AmiGoDOS(win) via integrated WebSocket server.. plus.. when the serial in/out is relayed via TCP-socket we can even create our own network of interconnected ScalaMMs.. think of it.. ScalaMM also has MIDI out so lots of potential fun experimenting with such a poweruser-setup.. i.e. generating effects in the webpage.. so now I need to run multiple instances in 1 webpage just like with BattleChess, Music-X or other successfull experiments.. :-)
4. SysInfo gives a whopping 68020E 99Mhz and states "Excellent".. but a JIT-less vAmigaWeb 68020E runs best at 14Mhz though going faster means often slower for a lot of cycle-exact-demanding software..
5. Although AmiBlitz3 IDE could never run to the fullest in the restricted vAmigaWeb environment.. I managed to get it to work in headless mode which consumes less memory.. and should makes any Blitz developer happy.. :-)
6. t.b.c. 

Buggy Experiences: with Chromium122 

1. GPU acceleration does not work anymore.. vAmigaWeb turns it off with a message..
2. we may need more usercontrol over "naming" the Snapshots.. I like saving as Amy,Buffy,Claire or A500 that worked before..  so when loading AmiGoDOS.php?amiga=Amy&mode=2&autoboot results in "booting" the named Snapshot with Serial-AUX: access.. with 2.6 I get a lot of problems with the storage mechanism..
3. WebStorage gives problems as I experienced nasty STATUS_ACCESS_VIOLATION errors.. while restoring.. loss of saved sessions.. and more cache/webstorage related "misery".. 
4. t.b.c.

I have to doublecheck those issues with FireFox to be more specific considering possible browser bugs..

That's it for now but I will edit/update this post when more testresults are available..
![vAmigaWeb_Core_2_6_beta_test1](https://github.com/vAmigaWeb/uat/assets/87427309/f25d6529-35ff-45db-8b2b-446f3e22e748)

![vAmigaWeb_Core_2_6_beta_test2](https://github.com/vAmigaWeb/uat/assets/87427309/eebb3c94-ac25-46bd-ab6b-ed57ad74a14e)

**Comment by mithrendal** [comment]
I am currently in holidays … I just flew over your comments…

>Chromium122 GPU acceleration does not work anymore.. vAmigaWeb turns it off with a message..

Just a quick response before I go to the beach again… when this happens then it’s likely the case that the browser does not offer a webgl2 context and vAmigaWeb detects this and falls back to simple canvas drawing.

For interlace resolutions you need the webgl renderer otherwise it looks ugly and does a lot of flickering when using the Amiga interlace resolutions…

I bet you have to enable webgl2 in your chromium 122 and it will work as usually


EDIT: also don’t use the current uat. Better use the 2.6 version at the regular address (I don’t know in what state the uat currently is)
